include $(TOPDIR)/rules.mk

LUCI_TITLE:=FanchMWRT Security Center
LUCI_DEPENDS:=+luci-base +fwxd +luci-compat +luci-lib-ipkg
LUCI_PKGARCH:=all
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
